# NvChad TokyoNight (custom)
background #16161e
foreground #a9b1d6

selection_background #2f3549
selection_foreground #a9b1d6

cursor #7aa2f7
cursor_text_color #1a1b26

url_color #7dcfff

color0  #1a1b26
color8 #555c7b

color1  #f7768e
color9  #f7768e

color2  #9ece6a
color10 #9ece6a

color3  #e0af68
color11 #e0af68

color4  #7aa2f7
color12 #2ac3de

color5  #bb9af7
color13 #9d7cd8

color6  #7dcfff
color14 #b4f9f8

color7  #a9b1d6
color15 #d5d6db

#background #16161e
#foreground #cdd6f4

#color0  #0f0f14
#color1  #f38ba8
#color2  #a6e3a1
#color3  #f9e2af
#color4  #6ea8fe
#color5  #b4befe
#color6  #89dceb
#color7  #cdd6f4

#cursor #6ea8fe
#selection_background #1e2230
