backend = "glx";
vsync = true;

# 阴影
shadow = true;
shadow-radius = 10;
shadow-opacity = 0.35;

# 淡入淡出
fading = true;

# 圆角（如果安装了 picom-ftlabs）
corner-radius = 12;

# 透明
inactive-opacity = 0.92;
active-opacity = 1.0;
frame-opacity = 0.95;

# 避免拖动卡顿
use-damage = true;

rounded-corners-exclude = [
    "class_g = 'i3bar'",
    "window_type = 'dock'"
];

shadow-exclude = [
  "name = 'Notification'",
  "class_g = 'Conky'",
  "class_g ?= 'Notify-osd'",
  "class_g = 'Cairo-clock'",
  "_GTK_FRAME_EXTENTS@:c",
  "class_g = 'Thunar'"    # 添加这行，为 Thunar 禁用阴影
];
