#!/bin/sh

f="$HOME/Picture/Screenshots/$(date +%Y-%m-%d-%H-%M-%S)-screenshot.png"

maim -s "$f"
xclip -selection clipboard -t image/png -i "$f"
notify-send "Selection screenshot copied to clipboard"
