#!/bin/sh

f="$HOME/Picture/Screenshots/$(date +%Y-%m-%d-%H-%M-%S)-screenshot.png"

maim -i "$(xdotool getactivewindow)" "$f"
xclip -selection clipboard -t image/png -i "$f"
notify-send "Window screenshot copied to clipboard"
